networks:
  internal:
    driver: bridge

services:
  markdown-converter:
    build: Document-to-Markdown
    restart: always
    ports:
      - "8501:8501"
    network_mode: bridge  # Explicitly set bridge mode to avoid Podman pods
    environment:
      OLLAMA_BASE_URL: http://host.containers.internal:11434  # Podman-specific host access
    # Uncomment for Docker
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"  # Allow access to host.docker.internal
